### PR TITLE
Fixed negative flag

### LINKED ISSUE #10: Negative flag doesn't work as expected
Test should **FAIL** but it's **OK** (chai v4.1.2):
```javascript
describe('chai-events', function() {
    const eventEmitter = new EventEmitter();

    it('should not emit', async function() {
        const onEventA = expect(eventEmitter).to.have.not.been.emit('eventA');
        eventEmitter.emit('eventA');
        await onEventA;
    });
});
```

**Root cause:** 
https://github.com/CodeLenny/chai-events/blob/master/chai-events.js#L71
```javascript
if(utils.flag(this, 'negate')) {
...
    assert(false, "expected #{this} to not emit "+name.toString()+".");
...
}
```
If you look at `chai.Assertion.assert()` API you can see that `util.test(this, arguments)` converts `expr` from `false` to `true` if negative flag is turned **ON** 

https://github.com/chaijs/chai/blob/master/chai.js#L231
```javascript
Assertion.prototype.assert = function (expr, msg, negateMsg, expected, _actual, showDiff) {
  var ok = util.test(this, arguments);
  ...
  if (!ok) {
    ...
    throw new AssertionError(...)
  };
```

https://github.com/chaijs/chai/blob/master/lib/chai/utils/test.js#L27
```javascript
module.exports = function test(obj, args) {
  var negate = flag(obj, 'negate')
    , expr = args[0];
  return negate ? !expr : expr;
};
```

**Fix:** Change wrong `assert()` usage to:
```
assert(true, '', 'expected #{this} to not emit '+name.toString() + '.');
```

### PR DESCRIPTION
**Pull request by CodeLenny**
Closes #10

### CODE REVIEW

File: chai-events.js [hunk 1]
```diff
@@ -95,7 +95,7 @@ function plugin(chai, utils) {
           if(done) { return; }
           done = true;
           try {
-            assert(false, "expected #{this} to emit "+name.toString()+".");
+            assert(false, '', "expected #{this} to emit "+name.toString()+".");
```
Comment (andrewvsk) [inline chai-events.js]: No need this changes here. Previous assert was corect. 
First assert() message is about 'positive' case and second for 'negative' (flag)

**Review by andrewvsk — COMMENTED** [review]
Also you can optimize your implementation:
```javascript
Assertion.addMethod('emit', function(name, timeout) {
    timeout   = timeout || 1500;
    const obj = utils.flag(this, 'object'); // this._obj

    const assert = expr => {
         //                         .not = false                              .not = true
         this.assert(expr, `expected #{this} to emit '${name}'`, `expected #{this} to not emit '${name}'`);
    };

    return new Promise((resolve, reject) => {
        let done = false;

        obj.once(name, (...args) => {
            try {
                if (done) return;
                done = true;

                assert(true);   // OK | ERROR (.not = true),

                resolve(args);
            } catch (err) {
                reject(err);
            }
        });

        setTimeout(() => {
            try {
                if (done) return;
                done = true;

                assert(false); // ERROR | OK (.not = true),

                resolve();
            } catch (err) {
                reject(err);
            }
        }, timeout);
    });
});
```
'if (done)' - is unnecessary if on event clears timer. But with 'done' code looks more understandable.

File: chai-events.js (hunk 1 above)
Comment (CodeLenny) [reply chai-events.js]: ~~Hmm, looks like you're right.  The `AssertionError` didn't seem to have the right message without the extra quotes, but I can't figure out why.  Looks like I'll revert it!~~

EDIT: Oops, figured it out, thanks!
